site_name: SE Portfolio
site_description: HBO-ICT Software Engineering Portfolio
site_author: HBO-ICT
copyright: Copyright 2023 Hogeschool van Amsterdam

theme:
    name: material
    custom_dir: mdocotion/
    features:
        - navigation.sections
        - content.tabs.link

plugins:
    - search
    - mermaid2
    - awesome-pages
    - mkdocs-video
    - section-index
    - autolinks
    - macros:
          modules: [mkdocs_macros_mdocotion]

markdown_extensions:
    - attr_list
    - md_in_html
    - fenced_code
    - pymdownx.highlight:
          linenums: true
          use_pygments: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - pymdownx.superfences:
          custom_fences:
                - name: mermaid
                  class: mermaid
                  format: !!python/name:pymdownx.superfences.fence_code_format

    
